### ISSUE TITLE
need custom command

### ISSUE THREAD

**Issue by wcdfilll** [LiteLDev/LiteLoaderPlugins#19]
I would like to comment that, if FakeNameDetection -> true then the custom command "ban ban" also works with it. There were a lot of people going in and out and I couldn't quickly write down their names, which was quite a disadvantage. I don't know if it's a bug but it seems that's it by default so I'm leaving the topic as "more features".
![image](https://user-images.githubusercontent.com/53313122/147866985-2ebd6486-c2f2-4e0b-8e9a-87cbd3083a13.png)

**Comment by dreamguxiang** [comment]
ok，Added in the next version

**Comment by ShrBox** [comment]
why not check `logs/AntiToolbox.log`
